version: '3.7'
services:
  api:
    build: .
    ports:
      - 3002:3000
    volumes:
      - ./src:/usr/src/app
    command: npm run dev
  postgres:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    volumes:
      - ./data:/bitnami/postgresql
    environment:
      POSTGRESQL_USERNAME: admin
      POSTGRESQL_PASSWORD: admin
      POSTGRESQL_DATABASE: todo